### ISSUE TITLE
bng_to_ll function

### ISSUE THREAD

**Issue by adamrobinson361** [dfe-analytical-services/dfeR#14]
**Background**

As discussed can we create a function that maps easting's and northings to long lat. Easting northing is the default format provided by [Get information about schools](https://get-information-schools.service.gov.uk/) but doesnt play particularly nicely with leaflet and needs converting. A function that could convert into the correct format without having to fully understand re projections would help in getting people plotting school level interactive data.

**Steps to take**

Steps to take

1.Create basic function with error handling to only accept doubles.
2. Put this in a new script in r folder called mapping.R
3. Document using roxygen as per other functions
4. roxygenise() the function to create md in man folder
5. Decide on unit tests you want to apply e.g. testing error handling and examples that you know answer for. 
6. Create these tests using test_that in tests/testthat folder.
7. Decide on better name. Current one relies on knowing acronyms

**Note:** How to can be found here or feel free to get in touch

**Comment by adamrobinson361** [comment]
Further research showed that there is existing functionality in sp package that does this very easily so not going to progress with this.

**Comment by matt-dray** [comment]
We should probably be looking at package `sf` for simple spatial stuff in the department. See function `st_transform`: https://www.rdocumentation.org/packages/sf/versions/0.6-0/topics/st_transform
