### ISSUE TITLE
Add dfe proxy function

### ISSUE THREAD

**Issue by adamrobinson361** [dfe-analytical-services/dfeR#3]
**Background**

Add a function that can be used to generate the proxy credentials for R

**Comment by peterrobertcurtis** [comment]
Adam suggested looking into using windows authentication.  It's a little beyond my knowledge, but I'm going to see what I can get working. 

Regarding dependency-free inputs, a simple readlines() can get inputs from the console, or utils::winDialogString can do the same from a dialog box. I'll add it as an option.

**Comment by peterrobertcurtis** [comment]
The package https://github.com/r-lib/keyring looks like it can access windows credentials.  I'm not volunteering to implement it (I have no time right now), but this may be a viable way forward
