### ISSUE TITLE
Port govstyle to dfeR

### ISSUE THREAD

**Issue by adamrobinson361** [dfe-analytical-services/dfeR#33]
**Background**

[govstyle](https://github.com/ukgovdatascience/govstyle) is an R package created by GDS that formats ggplots to standard styles as predefined to GDS. 

It is no longer maintained nor does it match the DfE style exactly. It would be good to add this into dfeR with correct styling so it can be more widely adopted. Alongside the markdown theme it would allow us to easily and consistently format our publications and internal reports. 

**Steps to take**

1. Understand [govstyle](https://github.com/ukgovdatascience/govstyle) code. 
2. Define dfe theme. See matts [gist](https://gist.github.com/matt-dray/657bdc6a63bd83830ef7130c572c310a)
3. Implement and test

**Comment by cwthom** [comment]
Is there a defined DfE style guide? Best I could find on the intranet was [this document from 2016](https://educationgovuk.sharepoint.com/:w:/r/sites/srg/a/_layouts/15/WopiFrame.aspx?sourcedoc=%7BC0C34CF4-067B-42C0-B43C-4F8001DD7653%7D&file=Graphs%20-%20%27how%20to%27%20guide.docx&action=default&DefaultItemOpen=1).

**Comment by adamrobinson361** [comment]
@matt-dray - Would be interested to see the doc you've got. I've definitely come accross approved colour lists in the past - not so sure about chart styles. Nevertheless it would be good if we could define one that we consistently use and encourage others to do so.

**Comment by lauraselby** [comment]
we did some stuff with govstyle for our Shiny app, but we didn't incorporate it efficiently. 
I think it's worth bringing HoP office in on this or the statistical policies working group (they're meeting tomorrow). The first step would be to decide if we (still?) want a DfE style that differs to GDS?
