### ISSUE TITLE
Standardised plotting

### ISSUE THREAD

**Issue by rmbielby** [dfe-analytical-services/dfeR#50]
Not sure if this needs to be it's own package (dfeplot?), but need some things to help style plots consistently.

**Comment by cjrace** [comment]
Think it would be sensible to include in here as it's dfe-specific recommended general R functions. Other packages to consider joining up with as we do it would be:
- [dfeshiny ](https://github.com/dfe-analytical-services/dfeshiny) - I'd expect static plot code lives here in dfeR, and then that can easily be combined with something in dfeshiny for reactivity?
- [afcolours](https://github.com/best-practice-and-impact/afcolours) - where we should be aiming to pull our default colours from (though following the [AF colours guidance](https://analysisfunction.civilservice.gov.uk/policy-store/data-visualisation-colours-in-charts/) we can look to add more and use the instructions for testing our own)
- [ggdfe](https://github.com/DfE-R-Community/ggdfe) - a similar package started elsewhere in DfE

**Comment by cjrace** [comment]
Expect this will be handled in https://github.com/best-practice-and-impact/afcharts
