### ISSUE TITLE
Find a way to make use of the `praise` package

### ISSUE THREAD

**Issue by cjrace** [dfe-analytical-services/dfeR#61]
**Is your feature request related to a problem? Please describe.**
This package looks great - https://github.com/rladies/praise

**Describe the solution you'd like**
We should find a way to build this package into messages for PRs and in the console when developing.

**Describe alternatives you've considered**
None.

**Additional context**
Coding is fun, and this is a simple but fun way to share enthusiasm

**Comment by JT-39** [comment]
Added https://github.com/dfe-analytical-services/dfeR/pull/71/commits/67f973b70c33a3e56c0c8eeeb06870ee9a4a4106
