### ISSUE TITLE
create_project() has too high a cyclomatic complexity score in linting

### ISSUE THREAD

**Issue by cjrace** [dfe-analytical-services/dfeR#77]
## Describe the bug
In the linting the `create_project()` function is failing on cyclocomp checks.

## How to reproduce
Steps to reproduce the behaviour:
1. Look at the actions logs - 

## Expected behaviour
This linting check should pass

## Screenshots
![image](https://github.com/user-attachments/assets/ba95940a-f7a5-45c2-b9d2-0cad79b3d894)

## Additional context
From the top of my head I think this is a count of the if / else statements within the function and intended to keep functions from getting overly complex and twisty with various different potential paths. Worth checking Hadley's R packages guide and anything we can find around CRAN guidance on this. Potentially breaking out smaller helper functions might help?

**Comment by jen-machin** [comment]
This is a nice beginner intro to cyclomatic complexity in case anyone is curious: https://linearb.io/blog/reduce-cyclomatic-complexity
